services:
  devcontainer:
    image: mdnf1992/cpp-dev
    volumes:
      - ../..:/workspaces/:cached
    ports:
      - "50051:50051"
    command: sleep infinity

  envoy:
    image: envoyproxy/envoy:v1.28.0
    ports:
      - "8080:8080"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml:ro
    depends_on:
      - devcontainer