name: C++ CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with: 
        submodules: true

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Pull Docker image
      run: docker pull --platform linux/arm64 mdnf1992/cpp-dev 

    - name: Build application & Test
      run: |
        docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace mdnf1992/cpp-dev /bin/bash -c "mkdir build && cd build && cmake .. && make && ctest"